# Generated by Django 5.0.3 on 2024-04-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Unesite upit', max_length=1000)),
                ('jezik', models.CharField(help_text='Odaberite jezik!', max_length=16)),
            ],
        ),
    ]
