# Generated by Django 5.0.3 on 2024-04-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='text',
            new_name='query',
        ),
        migrations.AddField(
            model_name='language',
            name='lid',
            field=models.CharField(default='sr', help_text='Unesite kratak naziv jezika', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='reply',
            field=models.TextField(default='default', help_text='Unesite odgovor', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Unesite jezik', max_length=16, unique=True),
        ),
    ]
