# Generated by Django 5.0.3 on 2024-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_text_query_query_language_lid_query_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField(default='System prpmpt', help_text='Enter parameter value', max_length=2048)),
                ('ctxpre', models.CharField(blank=True, help_text='Enter parameter value', max_length=80)),
                ('msg_content', models.CharField(blank=True, help_text='Enter parameter value', max_length=80)),
                ('min_len', models.IntegerField(default=40, help_text='Enter parameter value')),
                ('CHUNK_SIZE', models.IntegerField(default=800, help_text='Enter parameter value')),
                ('CHUNK_OVERLAP', models.IntegerField(default=50, help_text='Enter parameter value')),
                ('max_results', models.IntegerField(default=3, help_text='Enter parameter value')),
                ('EMBED_MODEL', models.CharField(default='embeddings model', help_text='Enter parameter value', max_length=256)),
                ('model_id', models.CharField(default='LLM model', help_text='Enter parameter value', max_length=256)),
                ('max_conv', models.IntegerField(default=3, help_text='Enter parameter value')),
                ('min_distance', models.FloatField(default=0.35, help_text='Enter parameter value')),
                ('max_distance', models.FloatField(default=0.6, help_text='Enter parameter value')),
                ('temperature', models.FloatField(default=0.55, help_text='Enter parameter value')),
                ('max_tokens', models.IntegerField(default=3072, help_text='Enter parameter value')),
                ('top_p', models.FloatField(default=0.8, help_text='Enter parameter value')),
                ('frequency_penalty', models.FloatField(default=0.0, help_text='Enter parameter value')),
                ('presence_penalty', models.FloatField(default=0.0, help_text='Enter parameter value')),
                ('DEBUG', models.BooleanField(default=True, help_text='Enter parameter value')),
                ('jezik', models.CharField(default='srpski', help_text='Uneti jezik', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='lid',
            field=models.CharField(default='sr', help_text='Unesite kratak naziv jezika', max_length=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='srpski', help_text='Unesite jezik', max_length=16, unique=True),
        ),
    ]
